apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redis
spec:
  rules:
    - host: redis.10.7.0.157.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: redis72rc3
                port:
                  number: 6379

